// Gin, Rum, and Tequila & Mezcal items for the After-Dinner / Spirits menu.
// Real Pelican Club content — Spirits PDF, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { SpiritListItem } from "./types";
import { spiritsMenuId, sGin, sRum, sTequilaMezcal } from "./seed-spirits";

export const ginRumTequilaItems: SpiritListItem[] = [
  // ---- Gin ----------------------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 0,
    name: "Gordon's",
    price: "9",
    group: "Gin",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 1,
    name: "Beefeater",
    price: "10",
    group: "Gin",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 2,
    name: "Bombay",
    price: "10",
    group: "Gin",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 3,
    name: "Bombay Sapphire",
    price: "11",
    group: "Gin",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 4,
    name: "Tanqueray",
    price: "11",
    group: "Gin",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 5,
    name: "Hendrick's",
    price: "14",
    group: "Gin",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sGin.id,
    sortOrder: 6,
    name: "Nolet's",
    price: "18",
    group: "Gin",
  },
  // ---- Rum ----------------------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 0,
    name: "Don Q Silver",
    price: "9",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 1,
    name: "Bacardi Silver",
    price: "10",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 2,
    name: "Captain Morgan",
    price: "10",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 3,
    name: "Goslings",
    price: "10",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 4,
    name: "Mount Gay",
    price: "10",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 5,
    name: "Malibu",
    price: "10",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 6,
    name: "Plantation Pineapple",
    price: "12",
    group: "Rum",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRum.id,
    sortOrder: 7,
    name: "Diplomatico",
    price: "17",
    group: "Rum",
  },
  // ---- Tequila & Mezcal ---------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 0,
    name: "El Jimador",
    price: "9",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 1,
    name: "Calle 23 Silver",
    price: "10",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 2,
    name: "Calle 23 Reposado",
    price: "12",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 3,
    name: "Patron",
    price: "13",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 4,
    name: "Yuul Baal Mezcal",
    price: "14",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 5,
    name: "Calle 23 Añejo",
    price: "14",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 6,
    name: "Casamigos Silver",
    price: "15",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 7,
    name: "Casamigos Reposado",
    price: "16",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 8,
    name: "Casamigos Añejo",
    price: "18",
    group: "Tequila & Mezcal",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sTequilaMezcal.id,
    sortOrder: 9,
    name: "Don Julio 1942",
    price: "32",
    group: "Tequila & Mezcal",
  },
];
