// Whiskey & Bourbon and Rye items for the After-Dinner / Spirits menu.
// Real Pelican Club content — Spirits PDF, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { SpiritListItem } from "./types";
import { spiritsMenuId, sWhiskeyBourbon, sRye } from "./seed-spirits";

export const whiskeyItems: SpiritListItem[] = [
  // ---- Whiskey & Bourbon --------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 0,
    name: "Jack Daniels",
    originVarietal: "Tennessee Whiskey",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 1,
    name: "Jim Beam",
    originVarietal: "Kentucky Bourbon",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 2,
    name: "Jameson",
    originVarietal: "Irish",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 3,
    name: "Bushmills",
    originVarietal: "Irish",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 4,
    name: "Seagram's 7 Crown",
    originVarietal: "American Whiskey",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 5,
    name: "Tullamore Dew",
    originVarietal: "Irish",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 6,
    name: "Canadian Club",
    originVarietal: "Canadian Whiskey",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 7,
    name: "Seagram's VO",
    originVarietal: "Canadian Whiskey",
    price: "10",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 8,
    name: "Four Roses",
    originVarietal: "Kentucky",
    price: "11",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 9,
    name: "Maker's Mark",
    originVarietal: "Kentucky Bourbon",
    price: "11",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 10,
    name: "Crown Royal",
    originVarietal: "Canadian Whiskey",
    price: "11",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 11,
    name: "Bulleit",
    originVarietal: "Kentucky",
    price: "12",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 12,
    name: "1792 Small Batch",
    originVarietal: "Kentucky Bourbon",
    price: "13",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 13,
    name: "Elijah Craig Small Batch",
    originVarietal: "Kentucky Bourbon",
    price: "13",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 14,
    name: "Knob Creek 9YR Small Batch",
    originVarietal: "Kentucky Bourbon",
    price: "13",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 15,
    name: "Russell's Reserve 10YR",
    originVarietal: "Kentucky Bourbon",
    price: "13",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 16,
    name: "Angel's Envy",
    originVarietal: "Kentucky Bourbon",
    price: "14",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 17,
    name: "Michter's Small Batch",
    originVarietal: "Kentucky Bourbon",
    price: "14",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 18,
    name: "Rowan's Creek",
    originVarietal: "Kentucky",
    price: "14",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 19,
    name: "Red Breast 12YR",
    originVarietal: "Single Pot Still Irish",
    price: "14",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 20,
    name: "Basil Hayden's",
    originVarietal: "Kentucky Bourbon",
    price: "15",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 21,
    name: "Willett Pot Still Reserve",
    originVarietal: "Kentucky Bourbon",
    price: "15",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 22,
    name: "Four Roses Single Barrel",
    originVarietal: "Kentucky Bourbon",
    price: "16",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 23,
    name: "Woodford Reserve",
    originVarietal: "Kentucky Bourbon",
    price: "16",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 24,
    name: "Shibui Grain Select",
    originVarietal: "Japanese Whisky",
    price: "16",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 25,
    name: "Jefferson's Ocean Very Small Batch",
    originVarietal: "Kentucky Bourbon",
    price: "20",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 26,
    name: "Old Rip Van Winkle 10YR",
    originVarietal: "Bourbon · 53.5% ALC/VOL",
    price: "88",
    group: "Whiskey & Bourbon",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sWhiskeyBourbon.id,
    sortOrder: 27,
    name: "Van Winkle Special Reserve Lot B 12YR",
    originVarietal: "Bourbon · 45.2% ALC/VOL",
    price: "120",
    group: "Whiskey & Bourbon",
  },
  // ---- Rye ----------------------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 0,
    name: "Old Overholt",
    originVarietal: "Kentucky Rye",
    price: "10",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 1,
    name: "Bulleit 95 Rye",
    originVarietal: "Straight American",
    price: "12",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 2,
    name: "Russell's Reserve 6YR",
    originVarietal: "Kentucky Rye",
    price: "12",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 3,
    name: "Sazerac",
    originVarietal: "Kentucky Rye",
    price: "12",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 4,
    name: "High West Double Rye",
    originVarietal: "Whiskey",
    price: "15",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 5,
    name: "Michter's",
    originVarietal: "Kentucky Rye",
    price: "15",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 6,
    name: "High West Rendezvous Rye",
    originVarietal: "Whiskey",
    price: "16",
    group: "Rye",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sRye.id,
    sortOrder: 7,
    name: "Willett Small Batch 4YR",
    originVarietal: "Kentucky Rye Whiskey",
    price: "16",
    group: "Rye",
  },
];
