// Dinner menu: Entrées, Desserts, and Bread Service items.
// Real Pelican Club content — Restaurant Week PDF, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { FoodItem } from "./types";
import { dinnerMenuId, sEntrees, sDesserts, sBreadService } from "./seed-dinner";

export const dinnerMainItems: FoodItem[] = [
  // ── Entrées ───────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 0,
    name: "HALF FRIED CHICKEN",
    price: "28",
    gf: false,
    description:
      "served in an iron skillet with corn pudding, black eyed peas & collard greens, cojito cheese, housemade hot sauce",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 1,
    name: "PRIME PORK CHOP",
    price: "36",
    gf: true,
    description: "mustard sauce, bourbon molasses sweet potatoes, collard greens",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 2,
    name: "WHOLE CRISPY FISH",
    price: "36",
    gf: true,
    description: "citrus chili sauce, jasmine rice",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 3,
    name: "SEARED RARE AHI TUNA & CHINOIS SALAD",
    price: "36",
    gf: true,
    description: "ginger soy glaze, avocado",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 4,
    name: "PANÉED GULF FISH WITH CRAWFISH ÉTOUFFÉE",
    price: "38",
    gf: true,
    description: "jalapeño hollandaise, brabant potatoes, haricots verts",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 5,
    name: "LOUISIANA CIOPPINO - IN ITS OWN POT",
    price: "36",
    gf: true,
    description:
      "basil garlic tomato sauce, gulf fish, shrimp, scallops, mussels, clams, calamari, buttered linguine · VEGAN/VEGETARIAN OPTION AVAILABLE: $28 À LA CARTE / $49 PRIX FIXE",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 6,
    name: "SURF & TURF",
    price: "42",
    gf: false,
    surcharge: "(+$6)",
    description:
      "6 oz filet mignon, thai shrimp cake, lemongrass hollandaise, coconut cream scallion smashed red potatoes, DV",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 7,
    name: 'USDA "PRIME" BEEF RIBEYE',
    price: "46",
    gf: true,
    surcharge: "(+$10)",
    description: "trumpet mushrooms, red wine sauce, buttery mashed potatoes, DV",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 8,
    name: "12 OZ MUSTARD, WALNUT & HERB CRUSTED RACK OF LAMB",
    price: "46",
    gf: true,
    surcharge: "(+$10)",
    description: "mint-demi, buttery mashed potatoes, DV",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sEntrees.id,
    sortOrder: 9,
    name: "1 LB WHOLE MAINE LOBSTER & FRIED SHRIMP",
    price: "44",
    gf: true,
    surcharge: "(+$8)",
    description:
      "served butterflied, lemon garlic beurre blanc, baby potatoes, haricots verts · LIMITED QUANTITIES AVAILABLE",
  },

  // ── Desserts ──────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sDesserts.id,
    sortOrder: 0,
    name: "WHITE CHOCOLATE BREAD PUDDING",
    price: "10",
    gf: false,
    description: "white and dark chocolate sauces",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sDesserts.id,
    sortOrder: 1,
    name: "COCONUT CREAM PIE",
    price: "10",
    gf: false,
    description: "chocolate sauce, whipped cream",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sDesserts.id,
    sortOrder: 2,
    name: "BOURBON PECAN PIE",
    price: "10",
    gf: false,
    description: "chocolate sauce, ice cream",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sDesserts.id,
    sortOrder: 3,
    name: "FLOURLESS CHOCOLATE DECADENCE CAKE",
    price: "10",
    gf: true,
    description: "almonds",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sDesserts.id,
    sortOrder: 4,
    name: "GRAND MARNIER CRÈME BRÛLÉE",
    price: "10",
    gf: true,
    description: "fresh fruit",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sDesserts.id,
    sortOrder: 5,
    name: "SORBET & FRESH FRUIT",
    price: "10",
    gf: true,
  },

  // ── Bread Service ─────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sBreadService.id,
    sortOrder: 0,
    name: "BREAD SERVICE",
    price: "5",
    gf: false,
    description: "basket of our homemade focaccia bread and butter",
  },
];
