// Dinner menu: To Begin and Appetizers & Salads items.
// Real Pelican Club content — Restaurant Week PDF, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { FoodItem } from "./types";
import { dinnerMenuId, sToBegin, sAppsSalads } from "./seed-dinner";

export const dinnerStarterItems: FoodItem[] = [
  // ── To Begin ──────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sToBegin.id,
    sortOrder: 0,
    name: "CREAMY SHRIMP BISQUE",
    price: "10",
    gf: false,
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sToBegin.id,
    sortOrder: 1,
    name: "SHRIMP, CHICKEN, & SAUSAGE GUMBO",
    price: "10",
    gf: false,
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sToBegin.id,
    sortOrder: 2,
    name: "VEGAN CARROT COCONUT GINGER SOUP",
    price: "10",
    gf: true,
  },

  // ── Appetizers & Salads ───────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 0,
    name: "PELICAN CLUB BAKED OYSTERS",
    price: "17",
    gf: true,
    description: "applewood smoked bacon, parmesan, garlic herb butter",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 1,
    name: "SEAFOOD MARTINI",
    price: "17",
    gf: true,
    description:
      "crab, shrimp, lobster, creole potato salad, avocado, ravigote sauce",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 2,
    name: "HEIRLOOM TOMATO, BURRATA & WALNUT SALAD",
    price: "17",
    gf: true,
    description:
      "arugula, mixed lettuces, pickled red onions, creamy basil vinaigrette · VEGAN OPTION AVAILABLE",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 3,
    name: "ESCARGOTS EN CROUTE",
    price: "18",
    gf: true,
    description: "mixed mushroom duxelle, garlic butter, puff pastry",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 4,
    name: "SEARED SCALLOPS & ARTICHOKE",
    price: "20",
    gf: true,
    surcharge: "(+$3)",
    description: "lemon garlic beurre blanc",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 5,
    name: "KOREAN PORK STEAM BUN",
    price: "16",
    gf: false,
    description: "kewpie mayo, sriracha & hoisin sauces, asian slaw",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 6,
    name: "LITTLE GEM CAESAR",
    price: "17",
    gf: true,
    description:
      "Spanish boquerones white anchovies, parmesan, toasted breadcrumbs, cheese crostini · VEGETARIAN OPTION AVAILABLE",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 7,
    name: "NEW ORLEANS STYLE BBQ SHRIMP",
    price: "18",
    gf: true,
    description:
      "U/12 head-on shrimp served in cast iron skillet with garlic bread",
  },
  {
    id: uuidv4(),
    type: "food",
    menuId: dinnerMenuId,
    sectionId: sAppsSalads.id,
    sortOrder: 8,
    name: "TUNA POKE",
    price: "17",
    gf: true,
    description: "onions, avocado crema, mango, tortilla chips",
  },
];
