// Drinks menu: Beer & Cider and Cocktail items.
// Real Pelican Club content — Drink Menu.html pipe-delimited source, June 2026.
// N/A tag → nonAlcoholic:true; "na" in cocktail source → nonAlcoholicAvailable:true.
import { v4 as uuidv4 } from "uuid";
import type { BeerCiderItem, CocktailItem } from "./types";
import { drinksMenuId, sBeer, sCocktails } from "./seed-drinks";

export const beerItems: BeerCiderItem[] = [
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 0,
    name: "Gnarly Barley Jucifer IPA",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 1,
    name: "Urban South Paradise Park Lager",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 2,
    name: "Urban South Paradise Park Light",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 3,
    name: "Parish Brewing Canebrake",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 4,
    name: "Chimay Blue Label",
    price: "13",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 5,
    name: "Michelob Ultra",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 6,
    name: "Saint Arnold Dry Cider",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 7,
    name: "Stella Artois",
    price: "9",
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 8,
    name: "Athletic Run Wild IPA",
    price: "10",
    nonAlcoholic: true,
  },
  {
    id: uuidv4(),
    type: "beer_cider",
    menuId: drinksMenuId,
    sectionId: sBeer.id,
    sortOrder: 9,
    name: "Athletic Golden Ale",
    price: "10",
    nonAlcoholic: true,
  },
];

export const cocktailItems: CocktailItem[] = [
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 0,
    name: "Strawberry Lemonade",
    ingredients: "housemade strawberry vodka, lemon juice",
    price: "14.5",
    nonAlcoholicAvailable: true,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 1,
    name: "Black Cherry Manhattan",
    ingredients: "bourbon, angostura, amaro, luxardo cherry juice",
    price: "15",
    nonAlcoholicAvailable: false,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 2,
    name: "Classic Hurricane",
    ingredients:
      "light & dark rum, passion fruit syrup, orange & cranberry juice, fresh lime",
    price: "14.5",
    nonAlcoholicAvailable: true,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 3,
    name: "Pimm's Martini",
    ingredients:
      "housemade cucumber gin, Pimm's #1, lime juice, a splash of ginger beer",
    price: "14.5",
    nonAlcoholicAvailable: false,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 4,
    name: "Cool Hand Cuke",
    ingredients: "cucumber-infused gin, fresh lemon, cava",
    price: "14.5",
    nonAlcoholicAvailable: true,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 5,
    name: "Red Sangria",
    ingredients: "red wine, spiced simple syrup, orange liqueur, Cognac",
    price: "14",
    nonAlcoholicAvailable: false,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 6,
    name: "Storyville Spritzer",
    ingredients: "gin, Aperol, grapefruit juice, floated with cava",
    price: "14.5",
    nonAlcoholicAvailable: true,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 7,
    name: "Amaretto Sidecar",
    ingredients:
      "Amaretto, Dry Curaçao, fresh lemon juice, served up with a sugar rim",
    price: "16",
    nonAlcoholicAvailable: false,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 8,
    name: "Desert Bloom",
    ingredients: "Condesa Prickly Pear gin, fresh citrus, cranberry, cava",
    price: "14.5",
    nonAlcoholicAvailable: false,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 9,
    name: "Espresso Martini",
    ingredients:
      "house-infused vanilla vodka, Mr. Black coffee liqueur, housemade cold brew",
    price: "17",
    nonAlcoholicAvailable: false,
  },
  {
    id: uuidv4(),
    type: "cocktail",
    menuId: drinksMenuId,
    sectionId: sCocktails.id,
    sortOrder: 10,
    name: "Margarita del Fuego",
    ingredients: "mezcal, triple sec, jalapeño, fresh citrus",
    price: "15",
    nonAlcoholicAvailable: true,
  },
];
