// XO Collection and Digestifs items for the After-Dinner / Spirits menu.
// Real Pelican Club content — Spirits PDF, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { SpiritListItem } from "./types";
import { spiritsMenuId, sXO, sDigestifs } from "./seed-spirits";

export const xoDigestifsItems: SpiritListItem[] = [
  // ---- XO Collection (two-ounce pours) ------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 0,
    name: "Hennessy VSOP",
    originVarietal: "Cognac · France",
    price: "12",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 1,
    name: "Remy Martin VSOP",
    originVarietal: "Cognac · France",
    price: "13",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 2,
    name: "Hennessy VS",
    originVarietal: "Cognac · France",
    price: "16",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 3,
    name: "Don Q Rum XO",
    originVarietal: "Puerto Rico",
    price: "19",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 4,
    name: "Clement Rum XO",
    originVarietal: "Martinique",
    price: "22",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 5,
    name: "Rhum J.M. XO",
    originVarietal: "Martinique",
    price: "22",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 6,
    name: "Plantation Rum XO",
    originVarietal: "Barbados",
    price: "26",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 7,
    name: "Clos des Ducs Armagnac XO",
    originVarietal: "France",
    price: "29",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 8,
    name: "Martell Cordon Bleu",
    originVarietal: "France",
    price: "32",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 9,
    name: "Reviseur Cognac XO",
    originVarietal: "France",
    price: "36",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 10,
    name: "Martell Cognac XO",
    originVarietal: "France",
    price: "42",
    group: "XO Collection",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sXO.id,
    sortOrder: 11,
    name: "Courvoisier Cognac XO",
    originVarietal: "France",
    price: "48",
    group: "XO Collection",
  },
  // ---- Digestifs (two-ounce pours) ----------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 0,
    name: "Averna Amaro",
    price: "14",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 1,
    name: "Meletti Amaro",
    price: "10",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 2,
    name: "Fernet Branca",
    price: "10",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 3,
    name: "Romana Sambuca",
    price: "12",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 4,
    // Owner to confirm the exact brand name — flagged intentionally
    name: "Grappa — VERIFY BRAND",
    price: "15",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 5,
    name: "12 Ouzo",
    price: "14",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 6,
    name: "Drambuie",
    price: "12",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 7,
    name: "Frangelico",
    price: "10",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 8,
    name: "Nocello",
    price: "10",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 9,
    name: "Licor 43",
    price: "14",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 10,
    name: "Green Chartreuse",
    price: "14",
    group: "Digestifs",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sDigestifs.id,
    sortOrder: 11,
    name: "D.O.M B&B",
    price: "12",
    group: "Digestifs",
  },
];
