// Scotch and Vodka items for the After-Dinner / Spirits menu.
// Real Pelican Club content — Spirits PDF, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { SpiritListItem } from "./types";
import { spiritsMenuId, sScotch, sVodka } from "./seed-spirits";

export const scotchVodkaItems: SpiritListItem[] = [
  // ---- Scotch -------------------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 0,
    name: "Dewar's White Label",
    originVarietal: "Blended Scotch Whiskey",
    price: "9",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 1,
    name: "Glenmorangie 10YR",
    originVarietal: "Single Malt Highland",
    price: "12",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 2,
    name: "Glenfiddich 12YR",
    originVarietal: "Single Malt Highland",
    price: "12",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 3,
    name: "Johnnie Walker Black Label",
    originVarietal: "Blended Highland",
    price: "12",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 4,
    name: "Dalwhinnie Doublewood 12YR",
    originVarietal: "Single Malt Highland",
    price: "13",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 5,
    name: "Glenlivet 12YR",
    originVarietal: "Single Malt Highland",
    price: "14",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 6,
    name: "Glenmorangie 12YR",
    originVarietal: "Single Malt Highland",
    price: "15",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 7,
    name: "Laphroaig 10YR",
    originVarietal: "Single Malt Islay",
    price: "16",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 8,
    name: "Macallan 12YR",
    originVarietal: "Single Malt Highland",
    price: "17",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 9,
    name: "Lagavulin 8YR",
    originVarietal: "Single Malt Islay",
    price: "18",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 10,
    name: "Oban 14YR",
    originVarietal: "Single Malt Highland",
    price: "18",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 11,
    name: "Glenmorangie 18YR",
    originVarietal: "Single Malt Highland",
    price: "25",
    group: "Scotch",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sScotch.id,
    sortOrder: 12,
    name: "Glenfiddich 18YR Small Batch",
    originVarietal: "Single Malt Highland",
    price: "27",
    group: "Scotch",
  },
  // ---- Vodka --------------------------------------------------------------
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 0,
    name: "Stoli",
    price: "9",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 1,
    name: "Absolut",
    price: "10",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 2,
    name: "Stoli Citrus",
    price: "10",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 3,
    name: "Stoli Vanilla",
    price: "10",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 4,
    name: "Stoli Blueberry",
    price: "10",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 5,
    name: "Stoli Razberi",
    price: "10",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 6,
    name: "Stoli Orange",
    price: "10",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 7,
    name: "Tito's",
    price: "11",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 8,
    name: "Chopin",
    price: "12",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 9,
    name: "Grey Goose",
    price: "12",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 10,
    name: "Ketel One",
    price: "12",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 11,
    name: "Ciroc",
    price: "13",
    group: "Vodka",
  },
  {
    id: uuidv4(),
    type: "spirit_list",
    menuId: spiritsMenuId,
    sectionId: sVodka.id,
    sortOrder: 12,
    name: "Belvedere",
    price: "13.50",
    group: "Vodka",
  },
];
