// Drinks menu: wine by the glass items (Sparkling, White & Rosé, Red).
// Real Pelican Club content — Drink Menu.html pipe-delimited source, June 2026.
import { v4 as uuidv4 } from "uuid";
import type { WineByGlassItem } from "./types";
import { drinksMenuId, sSparkling, sWhiteRose, sRedWine } from "./seed-drinks";

export const wineItems: WineByGlassItem[] = [
  // ── Sparkling ──────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sSparkling.id,
    sortOrder: 0,
    name: "Arte Latino Cava Brut",
    regionVintage: "Spain · N/V",
    price: "12",
    group: "Sparkling",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sSparkling.id,
    sortOrder: 1,
    name: "Jeio Prosecco Rosé Millesimato Brut",
    regionVintage: "Italy '23",
    price: "13",
    group: "Sparkling",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sSparkling.id,
    sortOrder: 2,
    name: "Scharffenberger Brut Mendocino",
    regionVintage: "California · N/V",
    price: "14.5",
    group: "Sparkling",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sSparkling.id,
    sortOrder: 3,
    name: "Frè Brut",
    regionVintage: "California · Non-Alcoholic",
    price: "12.5",
    group: "Sparkling",
  },

  // ── White & Rosé ──────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 0,
    name: 'Henri Bourgeois "Petit Bourgeois" Sauvignon Blanc',
    regionVintage: "Loire, France '24",
    price: "12.5",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 1,
    name: "Maison Saleya Rosé",
    regionVintage: "Provence, France '25",
    price: "13",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 2,
    name: "Vietti Moscato d'Asti",
    regionVintage: "Italy '24",
    price: "13",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 3,
    name: "Crowded House Sauvignon Blanc",
    regionVintage: "Marlborough, New Zealand '24",
    price: "13",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 4,
    name: "Martin Ray Chardonnay",
    regionVintage: "Sonoma Coast, California '24",
    price: "13.5",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 5,
    name: "Louis Latour Ardèche Chardonnay",
    regionVintage: "France '23",
    price: "13.5",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 6,
    name: "Banfi San Angelo Pinot Grigio",
    regionVintage: "Tuscany '24",
    price: "13",
    group: "White & Rosé",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sWhiteRose.id,
    sortOrder: 7,
    name: "Abadía de San Campio Albariño",
    regionVintage: "Rías Baixas '23",
    price: "13",
    group: "White & Rosé",
  },

  // ── Red ───────────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 0,
    name: "Sottano Malbec",
    regionVintage: "Mendoza, Argentina '24",
    price: "13",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 1,
    name: "Chalk Hill Pinot Noir",
    regionVintage: "Sonoma Coast, California '23",
    price: "14.5",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 2,
    name: "Siduri Pinot Noir",
    regionVintage: "Willamette Valley, Oregon '22",
    price: "14",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 3,
    name: "Rodney Strong Reserve Cabernet Sauvignon",
    regionVintage: "Sonoma, California '20",
    price: "17.5",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 4,
    name: "Klinker Brick Cabernet Sauvignon",
    regionVintage: "Lodi, California '23",
    price: "14",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 5,
    name: "Ferrari-Carano Merlot",
    regionVintage: "Sonoma, California '22",
    price: "13.75",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 6,
    name: "Saint Cosme Côtes du Rhône",
    regionVintage: "France '24",
    price: "13.5",
    group: "Red",
  },
  {
    id: uuidv4(),
    type: "wine_by_glass",
    menuId: drinksMenuId,
    sectionId: sRedWine.id,
    sortOrder: 7,
    name: "Cecchi Chianti Classico Sangiovese",
    regionVintage: "Tuscany, Italy '24",
    price: "13",
    group: "Red",
  },
];
